### ISSUE TITLE
POST to basic authed resource fails

### ISSUE THREAD

**Issue by marcusramberg** [pokeb/asi-http-request#3] opened 2009-08-27 10:00 UTC
Seems like asi-http-request is throwing away the POST request body on the second request.

**Comment by pokeb** [comment] 2009-08-27 10:16
Hi

Thanks for your report. Can you provide more information on how you are supplying credentials? (eg [request setUsername:], the built-in dialog, via your delegate, etc)

Thanks

Ben

**Comment by zcohan** [comment] 2009-08-27 10:34
We're providing credentials using setUsername: and setPassword in the authenticationNeededForRequest delegate method.

Actually we've pinpointed the problem. It only occurs when the ASIFormDataRequest object includes file data to post, added using the setFile:forKey method.

I can give you a sample app if required.

**Comment by zcohan** [comment] 2009-08-27 10:50
using setData:forKey also causes this problem

**Comment by pokeb** [comment] 2009-08-27 11:00
Ok, have found the problem. The setFile / setData methods trigger the post body to be streamed from disk, and it looks like the temporary file ASIHTTPRequest creates for the body is being deleted when authentication fails.

Will try to get a fix up in the next couple of hours.

b

**Comment by pokeb** [comment] 2009-08-27 11:52
I think this problem should be fixed in the last commit - can you try it out your end?

Thanks

Ben

**Comment by pokeb** [comment] 2009-08-27 15:08
Confirmed fixed.

**Closed as completed by pokeb** 2009-08-27 15:08 UTC
