### ISSUE TITLE
ASIDownloadCache: value store to 'statusCode' is never read

### ISSUE THREAD

**Issue by marcetcheverry** [pokeb/asi-http-request#198] opened 2011-05-27 17:13 UTC
See line 174 in ASIDownloadCache.m

It is giving an analyzer warning in XCode 4

![Analyzer Warning](http://i.imgur.com/dwfLF.png)

```
...
    // Store the response code in a custom header so we can reuse it later

    // We'll change 304/Not Modified to 200/OK because this is likely to be us updating the cached headers with a conditional GET
    int statusCode = [request responseStatusCode];
    if (statusCode == 304) {
        statusCode = 200;
    }
    [responseHeaders setObject:[NSNumber numberWithInt:[request responseStatusCode]] forKey:@"X-ASIHTTPRequest-Response-Status-Code"];

    [responseHeaders writeToFile:headerPath atomically:NO];

    if ([request responseData]) {
        [[request responseData] writeToFile:dataPath atomically:NO];
    } else if ([request downloadDestinationPath] && ![[request downloadDestinationPath] isEqualToString:dataPath]) {
        NSError *error = nil;
        [[[[NSFileManager alloc] init] autorelease] copyItemAtPath:[request downloadDestinationPath] toPath:dataPath error:&error];
    }
    [[self accessLock] unlock];
}
```

**Comment by pokeb** [comment] 2011-05-28 10:30
Duplicate of gh-189, fixed with:

https://github.com/pokeb/asi-http-request/commit/cde3ef691fc77a51adc1ded8f815d0ca490439c5

**Closed as completed by pokeb** 2011-05-28 10:30 UTC
